# shortcut = "a"
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on

set -g set-clipboard on
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -in -selection clipboard"

bind i split-window -h -c "#{pane_current_path}"
bind o split-window -v -c "#{pane_current_path}"
bind w new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind b previous-window
bind n next-window

bind q kill-pane
bind C-q kill-window

set -g status-position top
set -g status-style bg=default
set -g status-justify left

set -g status-left "#[fg=blue,bg=default][Pane #P]"
set -g status-left-length 20

set -g status-right ""

set -g window-status-current-format "#[fg=cyan,bold] #I:#W "
set -g window-status-format "#[fg=gray] #I:#W "
